# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"#\n\x0emapper_request\x12\x11\n\tmapper_id\x18\x01 \x01(\t\"*\n\x05\x63hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"\x1f\n\rreducer_chunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x17\n\x03\x61\x63k\x12\x10\n\x08received\x18\x01 \x01(\t2a\n\x06master\x12-\n\x0e\x64ownload_files\x12\x0f.mapper_request\x1a\x06.chunk\"\x00\x30\x01\x12(\n\x0cupload_files\x12\x0e.reducer_chunk\x1a\x04.ack\"\x00(\x01\x62\x06proto3'
)




_MAPPER_REQUEST = _descriptor.Descriptor(
  name='mapper_request',
  full_name='mapper_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mapper_id', full_name='mapper_request.mapper_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=49,
)


_CHUNK = _descriptor.Descriptor(
  name='chunk',
  full_name='chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='chunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='chunk.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=93,
)


_REDUCER_CHUNK = _descriptor.Descriptor(
  name='reducer_chunk',
  full_name='reducer_chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='reducer_chunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=126,
)


_ACK = _descriptor.Descriptor(
  name='ack',
  full_name='ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='received', full_name='ack.received', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['mapper_request'] = _MAPPER_REQUEST
DESCRIPTOR.message_types_by_name['chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['reducer_chunk'] = _REDUCER_CHUNK
DESCRIPTOR.message_types_by_name['ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mapper_request = _reflection.GeneratedProtocolMessageType('mapper_request', (_message.Message,), {
  'DESCRIPTOR' : _MAPPER_REQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:mapper_request)
  })
_sym_db.RegisterMessage(mapper_request)

chunk = _reflection.GeneratedProtocolMessageType('chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:chunk)
  })
_sym_db.RegisterMessage(chunk)

reducer_chunk = _reflection.GeneratedProtocolMessageType('reducer_chunk', (_message.Message,), {
  'DESCRIPTOR' : _REDUCER_CHUNK,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:reducer_chunk)
  })
_sym_db.RegisterMessage(reducer_chunk)

ack = _reflection.GeneratedProtocolMessageType('ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ack)
  })
_sym_db.RegisterMessage(ack)



_MASTER = _descriptor.ServiceDescriptor(
  name='master',
  full_name='master',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=153,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='download_files',
    full_name='master.download_files',
    index=0,
    containing_service=None,
    input_type=_MAPPER_REQUEST,
    output_type=_CHUNK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='upload_files',
    full_name='master.upload_files',
    index=1,
    containing_service=None,
    input_type=_REDUCER_CHUNK,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['master'] = _MASTER

# @@protoc_insertion_point(module_scope)
